# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

replicas: 1

image:
  repository: atomix/controller
  tag: ""
  pullPolicy: ""
  pullSecrets: []

init:
  image:
    repository: atomix/controller-init
    tag: ""
    pullPolicy: ""
    pullSecrets: []

logging:
  rootLevel: info
  encoding: console
  loggers:
    github.com/micro-onos-revamped/atomix/runtime/pkg/utils/grpc/interceptors:
      level: error
